# Generated by Django 5.0 on 2024-01-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firebase_uid',
            field=models.CharField(default='some_default_value', max_length=255, unique=True),
        ),
    ]
