# Generated by Django 5.0 on 2024-01-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_user_firebase_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='firebase_uid',
            field=models.CharField(default='null', max_length=255, unique=True),
        ),
    ]
