# Generated by Django 5.0 on 2024-03-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_feedback_feedback_feedback_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='interview_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
