# Generated by Django 5.0 on 2024-03-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_interview_interview_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='user_interview_no',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
