# Generated by Django 5.0 on 2024-02-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_user_firebase_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrinterviewQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quesionlist', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalinterviewQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quesionlist', models.TextField()),
            ],
        ),
    ]
