# Generated by Django 5.0 on 2024-04-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_interview_user_interview_no_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='confidence_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='interview',
            name='grammer_score',
            field=models.FloatField(default=0),
        ),
    ]
